name: workflow
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}

jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Update
        run: |
          npx stargazed -u desiresprout -t ${{ secrets.STARGAZED_TOKEN }} -r awesome-stars -m "stargazed update" -s
